### ISSUE TITLE
Make dependency on language-data optional

### ISSUE THREAD

**Issue by BLKSerene** [georgkrause/langcodes#13]
Hi, `language-data` is an optional dependency for `langcodes` < 3.4, and it seems that the conditional imports are still [there](https://github.com/georgkrause/langcodes/blob/main/langcodes/__init__.py) in this fork. Is it possible to make this dependency optional?

**Comment by georgkrause** [comment]
@BLKSerene Thats possible for sure, can you explain me the usecase? I was considering merging the two packages into one to make it easier to maintain and run because I thought it wouldn't make sense to use langcodes without language_data. What am I missing?

**Comment by BLKSerene** [comment]
`langcodes` is a dependency of `spaCy` which only require short code conversion functionalities (see [this commit](https://github.com/explosion/spaCy/commit/53b5f245eda6dc3e88b84cba15c2a3f4df3cf4c2)). If you are going to merge two packages into one, that would be fine.
