### ISSUE TITLE
Closest Match for Punjabi (Pakistan) Not Resolving Match

### ISSUE THREAD

**Issue by georgkrause** [georgkrause/langcodes#5]
original issue: https://github.com/rspeer/langcodes/issues/59

**Comment by devdanzin** [comment]
We are working to fix this. Is the idea of adding an `ignore_script` argument to `closest_match` function the best way to solve this? Or maybe always adding script-less languages to `match_distances` as fallback?

**Comment by georgkrause** [comment]
This is going to be fixed by #17

**Comment by georgkrause** [comment]
Since we merged #17 I feel free to close the issue. If the problem remains, please let me know!
